set shell := ["nu", "-c"]

doc-host-location := x"${WEBSITE_LOCATION}/content/software/documentation/moonshine"

# Documentation

# Deploy documentation
doc-deploy:
    julia --project=docs docs/deploy.jl {{ doc-host-location }}

# Build documentation for current commit (set `mode` to `draft` to enable draft mode)
doc-make mode="": doc-check
    julia --project=docs --eval "import Pkg; Pkg.instantiate(); Pkg.precompile()"
    time julia --project=docs -- docs/make.jl {{ mode }}

# Serve documentation locally
doc-serve:
    julia --project=docs --eval "import LiveServer; LiveServer.serve(dir = \"docs/build\")"

# Check markdown files for dumb mistakes
[working-directory: "docs"]
doc-check:
    #!/usr/bin/env nu
    print $'(ansi rb)Checking(ansi reset_bold) for common mistakes...(ansi reset)'
    let mistakes = ls **/* | get name | where $it =~ '\.md$' | each { ./check-stupid-mistakes.awk $in } | compact --empty
    if ($mistakes | is-empty) {
        print $'(ansi g)No mistake found!(ansi reset)'
    } else {
        $mistakes
    }

# Release

# Release a new version
release type: (_release-increase-project-version type) && _tag-commit
    @print $'(ansi rb)Generating(ansi reset_bold) changelog...(ansi reset)'
    @run-external 'git' 'cliff' 'v0.2.0..' '--tag' (open Project.toml | get version) '--output' e> /dev/null

    @print $'(ansi rb)Creating(ansi reset_bold) commit...(ansi reset)'
    @git add CHANGELOG.md Project.toml
    @git commit -m $'Bump version to (open Project.toml | get version)'

_release-increase-project-version type:
    #!/usr/bin/env nu
    print $'(ansi rb)Increasing(ansi reset_bold) {{ type }} version in Project.toml...(ansi reset)'

    let current_version = open Project.toml |
        get version |
        split row '.' |
        each { $in | into int }

    mut num_to_update = 42
    if ('{{ type }}' == 'patch') {
        $num_to_update = 2
    } else if ('{{ type }}' == 'minor') {
        $num_to_update = 1
    } else if ('{{ type }}' == 'major') {
        $num_to_update = 0
    }
    let version = $current_version |
        update $num_to_update { $in + 1} |
        str join '.'

    const awk_script = '/^version/{print "version = \"" version "\""; next} {print}'
    run-external 'awk' '-i' 'inplace' '-v' $'version=($version)' $awk_script 'Project.toml'

_tag-commit:
    #!/usr/bin/env nu
    print $'(ansi rb)Creating(ansi reset_bold) tag...(ansi reset)'

    source ~/nushell/scripts/ollama.nu

    let last_tag = git describe --abbrev=0
    let new_tag = [ 'v' (open Project.toml | get version) ] | str join

    let changes = git cliff --unreleased e> /dev/null |
        lines |
        skip 2 |
        str join "\n"

    mut message = [ 'You will be provided a markdown-formatted list of changes for a new release of a Julia package. Your job is to produce a summary that will be attached as a git tag message. The summary should take the form of a short introduction followed by a list. Your output will be used as is. With that in mind, summarize the following changes:' $changes ] |
        str join "\n" |
        ollamapi generate
    $message = [
        $'Moonshine ($new_tag)'
        $"[Diff since ($last_tag)]\(https://codeberg.org/ptrk/Moonshine.jl/compare/($last_tag)...($new_tag)\)"
        $message
        $"[Complete changelog]\(https://codeberg.org/ptrk/Moonshine.jl/src/tag/($new_tag)/CHANGELOG.md\)"
        '*Summary generated by Gemma 4 12b*' ] | str join "\n\n"

    git tag -s -a $new_tag -m $message
